# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build blog
      run: |
        apt-get update -y && apt-get install wget
        wget https://github.com/gohugoio/hugo/releases/download/v0.76.1/hugo_extended_0.76.1_Linux-64bit.deb
        dpkg -i hugo*.deb
        hugo
        git add . 
        git commit -m "built website"
        git push
